version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/usr/share/nginx/html
      
    environment:
      - NODE_ENV=production

    command: ["nginx", "-g", "daemon off;"]

volumes:
  app-data: